### ISSUE TITLE
Filter drop downs are ew

### ISSUE THREAD

**Issue by MHalseyPerry** [jake-milo/janda#7]
Whole of filter selection should activate drop down, default drop down is nasty.

**Comment by jakewtaylor** [comment]
I think this has been covered? I'll probably need to add in a custom select that allows searching at some point, but I'm closing this for now.

**Comment by MHalseyPerry** [comment]
👌

**Comment by jakewtaylor** [comment]
We got `FilterableSelect` now!

463b70ec8db65ee23c6c20d1a70336a1402716c5
